hexo_migrator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
]

web/urls.py
from django.urls import path, re_path
from . import views

app_name = 'web'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('home/', views.Home.as_view(), name='home'),
    path('blog/add/', views.BlogAddEditView.as_view(), name='blog_add'),
    re_path('blog/edit/(?P<pk>\d+)/', views.BlogAddEditView.as_view(), name='blog_edit'),
    re_path('blog/del/(?P<pk>\d+)/', views.blog_del_view, name='blog_del'),
    re_path('blog/permanent/del/(?P<pk>\d+)/', views.blog_permanent_del_view, name='blog_permanent_del'),
    re_path('blog/restore/(?P<pk>\d+)/', views.blog_restore_view, name='blog_restore'),
    path('categories/list/', views.CategoriesView.as_view(), name='categories_list'),
    path('categories/add/', views.CategoriesAddEditView.as_view(), name='categories_add'),
    re_path('categories/edit/(?P<pk>\d+)/', views.CategoriesAddEditView.as_view(), name='categories_edit'),
    re_path('categories/del/(?P<pk>\d+)/', views.categories_del_view, name='categories_del'),
    re_path('categories/permanent/del/(?P<pk>\d+)/', views.categories_permanent_del_view, name='categories_permanent_del'),
    re_path('categories/restore/(?P<pk>\d+)/', views.categories_restore_view, name='categories_restore'),
    path('categories/bulk/create', views.categories_bulk_create, name='categories_bulk_create'),
    path('tags/add/', views.TagsAddEditView.as_view(), name='tags_add'),
    re_path('tags/edit/(?P<pk>\d+)/', views.TagsAddEditView.as_view(), name='tags_edit'),
    re_path('tags/del/(?P<pk>\d+)/', views.tags_del_view, name='tags_del'),
    re_path('tags/permanent/del/(?P<pk>\d+)/', views.tags_permanent_del_view, name='tags_permanent_del'),
    re_path('tags/restore/(?P<pk>\d+)/', views.tags_restore_view, name='tags_restore'),
    path('import/old/', views.BulkImportOld.as_view(), name='bulk_import_old'),
    path('import/original/', views.BulkImportOriginal.as_view(), name='bulk_import_original'),
    path('bulk/hexo/generate/', views.bulk_hexo_generate, name='bulk_hexo_generate'),
    path('one/click/', views.one_click, name='one_click'),
    path('hexo/build/', views.hexo_build, name='hexo_build'),
]

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Hexo Migrator</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    {% block css %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'web:home' %}">首页</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'web:categories_list' %}">管理分类和标签</a></li>
                <li><a href="{% url 'web:bulk_hexo_generate' %}">批量生成 Hexo 博客文件</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">博客操作<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'web:bulk_import_old' %}">从现有博客导入</a></li>
                        <li><a href="{% url 'web:categories_bulk_create' %}">批量导入分类</a></li>
                        <li><a href="{% url 'web:bulk_import_original' %}">导入新写好的博客原文件</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'web:logout' %}">注销</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
</body>
<script src="{% static 'jquery.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
{% block js %}
{% endblock %}
</html>

web/templates/blog_add_edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for foo in form_obj %}
                    <div class="form-group">
                        <span style="color: red">{{ foo.errors.0 }}</span>
                        <label for="{{ foo.id_for_label }}" class="col-sm-2 control-label">{{ foo.label }}</label>
                        <div class="col-sm-10">
                            {{ foo }}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

web/templates/categories_add_edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for foo in form_obj %}
                    <div class="form-group">
                        <span style="color: red">{{ foo.errors.0 }}</span>
                        <label for="{{ foo.id_for_label }}" class="col-sm-2 control-label">{{ foo.label }}</label>
                        <div class="col-sm-10">
                            {{ foo }}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

web/templates/categories_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4">
            <a href="{% url 'web:categories_add' %}" class="btn btn-success">新建分类</a>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>外层文件夹名</th>
                    <th>分类名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for categories in categories_list %}
                    <tr>
                        <td>{{ categories.wrapper_folder }}</td>
                        <td>{{ categories.category_name }}</td>
                        <td>
                            <a href="{% url 'web:categories_edit' categories.pk %}" class="btn btn-info btn-xs" title="修改">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                            <a href="{% url 'web:categories_del' categories.pk %}" class="btn btn-danger btn-xs" title="删除">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-4 col-md-offset-4">
            <a href="{% url 'web:tags_add' %}" class="btn btn-success">新建标签</a>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>标签名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for tags in tags_list %}
                    <tr>
                    <td>{{ tags.tag_name }}</td>
                    <td>
                        <a href="{% url 'web:tags_edit' tags.pk %}" class="btn btn-info btn-xs" title="修改">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                        <a href="{% url 'web:tags_del' tags.pk %}" class="btn btn-danger btn-xs" title="删除">
                            <i class="glyphicon glyphicon-trash"></i>
                        </a>
                    </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    <hr>
    <h3 class="text-center">下面的是已经删除了的分类和标签</h3>
    <div class="row">
        <div class="col-md-4">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>外层文件夹名</th>
                    <th>分类名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for categories in categories_del_list %}
                    <tr>
                        <td>{{ categories.wrapper_folder }}</td>
                        <td>{{ categories.category_name }}</td>
                        <td>
                            <a href="{% url 'web:categories_restore' categories.pk %}" class="btn btn-success btn-xs" title="恢复">
                                <i class="glyphicon glyphicon-repeat"></i>
                            </a>
                            <a href="{% url 'web:categories_permanent_del' categories.pk %}"
                               class="btn btn-danger btn-xs" title="彻底删除">
                                <i class="glyphicon glyphicon-remove"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-4 col-md-offset-4">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>标签名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for tags in tags_del_list %}
                    <tr>
                    <td>{{ tags.tag_name }}</td>
                    <td>
                        <a href="{% url 'web:tags_restore' tags.pk %}" class="btn btn-success btn-xs" title="恢复">
                            <i class="glyphicon glyphicon-repeat"></i>
                        </a>
                        <a href="{% url 'web:tags_permanent_del' tags.pk %}" class="btn btn-danger btn-xs" title="彻底删除">
                            <i class="glyphicon glyphicon-remove"></i>
                        </a>
                    </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

web/templates/hexo_generate.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">批量生成 Hexo 博客文件</h2>
            <form class="form-horizontal" novalidate method="post">
                {% csrf_token %}
                <div class="form-group">
                    <span style="color: red">{{ form_obj.target_blog_path.errors.0 }}</span>
                    <label for="{{ form_obj.target_blog_path.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.target_blog_path.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.target_blog_path }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">批量生成</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

web/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        博客总数：<strong>{{ blog_list.count }}</strong>
        字符总数：<strong>{{ count.char }}</strong>
        汉字总数：<strong>{{ count.hans }}</strong>
    </div>
    <a href="{% url 'web:blog_add' %}" class="btn btn-info">新建博客</a>
    <a href="{% url 'web:one_click' %}" class="btn btn-success">一键操作</a>
    <button class="btn btn-warning" id="hexo_build">Hexo 部署生成</button>
    <table class="table table-hover table-bordered">
        <thead>
        <tr>
            <th class="text-center">博客标题</th>
            <th class="text-center">博客分类</th>
            <th class="text-center">博客标签</th>
            <th class="text-center">有无描述</th>
            <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody class="text-center">
        {% for blog in blog_list %}
            <tr>
                <td>{{ blog.title }}</td>
                <td>{{ blog.categories }}</td>
                <td>{{ blog.show_tags }}</td>
                {% if blog.description %}
                    <td title="{{ blog.description }}" class="success">有</td>
                    {% else %}
                    <td class="danger">无</td>
                {% endif %}
                <td>
                    <a href="{% url 'web:blog_edit' blog.pk %}" class="btn btn-info btn-xs" title="编辑">
                        <i class="glyphicon glyphicon-edit"></i>
                    </a>
                    <a href="{% url 'web:blog_del' blog.pk %}" class="btn btn-danger btn-xs" title="删除">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <hr>
    <h3 class="text-center">下面是已经删除了的博客</h3>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>博客标题</th>
            <th>博客相对路径</th>
            <th>博客分类</th>
            <th>博客标签</th>
            <th>更新日期</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for blog in blog_del_list %}
            <tr>
                <td>{{ blog.title }}</td>
                <td>{{ blog.path }}</td>
                <td>{{ blog.categories }}</td>
                <td>{{ blog.show_tags }}</td>
                <td>{{ blog.update }}</td>
                <td>
                    <a href="{% url 'web:blog_restore' blog.pk %}" class="btn btn-success btn-xs" title="恢复">
                        <i class="glyphicon glyphicon-refresh"></i>
                    </a>
                    <a href="{% url 'web:blog_permanent_del' blog.pk %}" class="btn btn-danger btn-xs" title="彻底删除">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

{% block js %}
    <script>
    $(function(){
        $("#hexo_build").on("click",function(){
            $.ajax({
                // 后端程序的url地址
                url: '{% url "web:hexo_build" %}',
                // 也可以使用method，提交数据的方式，默认是'GET'，常用的还有'POST'
                type: 'get',
            })
            .done(function(resp) {     // 请求成功以后的操作
                console.log(resp);
            })
            .fail(function(error) {    // 请求失败以后的操作
                console.log(error);
            });
        });
    })
    </script>
{% endblock %}

web/templates/import_old.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">从现有博客文件中导入</h2>
            <form class="form-horizontal" novalidate method="post">
                {% csrf_token %}
                <div class="form-group">
                    <span style="color: red">{{ form_obj.old_blog_path.errors.0 }}</span>
                    <label for="{{ form_obj.old_blog_path.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.old_blog_path.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.old_blog_path }}
                    </div>
                </div>
                <div class="form-group">
                    <span style="color: red">{{ form_obj.target_blog_path.errors.0 }}</span>
                    <label for="{{ form_obj.target_blog_path.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.target_blog_path.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.target_blog_path }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">批量导入</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

web/templates/import_origin.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">导入新写好的博客原文件</h2>
            <form class="form-horizontal" novalidate method="post">
                {% csrf_token %}
                <div class="form-group">
                    <span style="color: red">{{ form_obj.old_blog_path.errors.0 }}</span>
                    <label for="{{ form_obj.old_blog_path.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.old_blog_path.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.old_blog_path }}
                    </div>
                </div>
                <div class="form-group">
                    <span style="color: red">{{ form_obj.target_blog_path.errors.0 }}</span>
                    <label for="{{ form_obj.target_blog_path.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.target_blog_path.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.target_blog_path }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">批量导入</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

web/templates/tags_add_edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for foo in form_obj %}
                    <div class="form-group">
                        <span style="color: red">{{ foo.errors.0 }}</span>
                        <label for="{{ foo.id_for_label }}" class="col-sm-2 control-label">{{ foo.label }}</label>
                        <div class="col-sm-10">
                            {{ foo }}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}